package com.myunsplash.backend;

import lombok.*;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Photos")
public class Photo {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  private String label;

  @DynamoDBAttribute
  private String url;

  public void setLabel(String label) {
    this.label = label.toLowerCase();
  }
}
